[programs.localnet]
ocr2 = "Fh7uhkZLvogdxrQccDpRgMDyN3wKb5ZQGRcpvujeqAae"
access_controller = "ENmeY9iRUUzN5NUvhHTc5vA8nQuYqXcsU7h4JzKMw5aE"
deviation_flagging_validator = "CVmCNhhYxQHRjWJuGDUio3JtNnsTfHTVWyTgq6UozQSw"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
# wallet = "~/.config/solana/id.json"
wallet = "id.json"

[scripts]
test = "yarn run test"
